apiVersion: v1
kind: Pod
metadata:
  name: sample-new
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: pods-simple-container-new
      envFrom:
       - configMapRef:
                name: job-name
       - configMapRef:
                name: build-tag
